<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>PureQL.CSharp.Model.OpenAPI.Schema</PackageId>
    <RootNamespace>PureQL.CSharp.Model.OpenAPI.Schema</RootNamespace>
    <AssemblyName>PureQL.CSharp.Model.OpenAPI.Schema</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/PureQL.CSharp.Model.OpenAPI.Schema</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>
</Project>
